
listen_on unix:/tmp/kitty.sock
include colors.conf

allow_remote_control yes

background #000000
cursor #93a1a1
cursor_text_color #002b36
cursor_beam 1
cursor_blinking yes
enable_3d true

confirm_os_window_close 0

# ---------------- Font ----------------
font_family JetBrains Nerd Font
bold_font   JetBrains Nerd Font
italic_font JetBrains Nerd Font
bold_italic_font JetBrains Nerd Font
font_size 14

# ---------------- Window ----------------
background_opacity 1
window_padding_width 16
window_margin_width 0
window_decorations none
adjust_line_height -2
placement_strategy top-left
