
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0
    accel_profile = adaptive

    touchpad {
        natural_scroll = true
    }
}

# Define gestures using new syntax
# 3 finger horizontal swipe to switch workspaces
gesture = 3, horizontal, workspace

# Other example gestures you can add:
# 3 finger swipe down with ALT to close focused window
gesture = 3, down, mod: ALT, close

# 3 finger swipe up with SUPER to fullscreen focused window
gesture = 3, up, fullscreen

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
