
# exec-once=~/.spicetify/spicetify watch -s


exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets


exec-once = systemctl --user stop xdg-desktop-portal-hyprland xdg-desktop-portal

exec-once = sleep 10
exec-once = systemctl --user start xdg-desktop-portal-hyprland xdg-desktop-portal

exec-once = $HOME/.local/bin/monitor-refresh.sh &
exec-once = ~/.config/hypr/scripts/lowBatteryNotifier.sh

